AGENT:
  ROLE: website search helper
  BACKSTORY: You are a specialized agent capable of generating multiple parameterized search engine links. For general information queries, provide direct links using popular search engines such as Google and Bing by appending query parameters to the URL. For resource retrieval and academic research, output specially designated links to academic databases and dedicated resource sites with the appropriate parameters embedded.
  TASK: null

RAG:
  RAG_ENABLE: false
#  MODULE_PATH: /Users/chenzi/project/module/bce-embedding-base_v1
  MODULE_PATH: null
  COLLECTION_NAME: mofa
  IS_UPLOAD_FILE: true
  CHROMA_PATH: ./data/output/chroma_store
  FILES_PATH:
    - ./data/output/arxiv_papers
  ENCODING: utf-8
  CHUNK_SIZE: 256
  RAG_SEARCH_NUM: 5
  RAG_MODEL_NAME: netease-youdao/bce-embedding-base_v1
  RAG_MODEL_API_URL: https://api.siliconflow.cn/v1
  RAG_MODEL_API_KEY:

WEB:
  WEB_ENABLE: false
  SERPER_API_KEY:
  SEARCH_NUM: 20
  SEARCH_ENGINE_TIMEOUT: 5

MODEL:
  MODEL_API_KEY: sk-rwdwblfaqhbalqgobftnpjaixpzrltpiqjjjpkunswdfdsat
  MODEL_NAME: deepseek-ai/DeepSeek-V2.5
  MODEL_MAX_TOKENS: 2048
  MODEL_API_URL: https://api.siliconflow.cn/v1/chat/completions
#  MODEL_API_KEY:
#  MODEL_NAME: gpt-4o-mini
#  MODEL_MAX_TOKENS: 2048

ENV:
  PROXY_URL: null
  AGENT_TYPE: reasoner

LOG:
  LOG_PATH: ./data/output/log/log.md
  LOG_TYPE: markdown
  LOG_STEP_NAME: reasoner_result
  CHECK_LOG_PROMPT: true

